story1_Jace/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story1/', include('myprofile.urls')),
    path('', include('story3ku.urls', namespace='story3')),
    path('story5/', include('story5.urls',namespace='story5')),
    path('story6/', include('story6.urls',namespace='story6')),
    path('story7/', include('story7.urls',namespace='story7')),
     path('story8/', include('story8.urls',namespace='story8')),
    path('story9/', include('story9.urls', namespace='story9')),
    path('story9/', include('django.contrib.auth.urls')),
]

story5/urls.py
from django.urls import path 
from . import views

app_name = 'story5'
urlpatterns = [
	path('delete/<str:delete_id>', views.delete, name='delete'),
	path('update/<str:update_id>', views.update, name='update'),
	path('create/', views.create, name='create'),
    path('', views.index, name='index'),

]

story6/urls.py
from django.urls import path 
from . import views

app_name = 'story6'
urlpatterns = [
	path('delete/<int:id_kegiatan>/', views.delete, name='delete'),
	path('deleteOrang/<int:id_peserta>/', views.deleteOrang, name='deleteOrang'),
	path('create/', views.createKegiatan, name='createActivity'),
	path('createPeserta/<int:id_orang>/', views.createPeserta, name='createPeserta'),
    path('', views.index, name='index'),

]

story6/models.py
from django.db import models


class PostKegiatan(models.Model):
    kegiatan = models.CharField(max_length=100)

class PostPeserta(models.Model):
    peserta = models.CharField(max_length=100)
    ikutKegiatan = models.ForeignKey(
        PostKegiatan, on_delete=models.CASCADE, null=True, blank=True)
# Create your models here.

story6/forms.py
from django import forms
from . models import PostKegiatan,PostPeserta

class KegiatanForm(forms.ModelForm):
    class Meta:
        model = PostKegiatan
        fields = [
            'kegiatan',
        ]

class PesertaForm(forms.ModelForm):
    class Meta:
        model = PostPeserta
        fields = [
            'peserta',
        ]

story6/views.py
from django.shortcuts import render,redirect

# Create your views here.
from .forms import KegiatanForm, PesertaForm
from .models import PostKegiatan, PostPeserta

def index(request):
    kegiatan = PostKegiatan.objects.all()
    peserta = PostPeserta.objects.all()

    context = {
        'page_title':'Story 6 Jace',
		'kegiatan': kegiatan,
        'peserta': peserta,
		'post_title': 'Kegiatan Saya dan Teman-teman',
		'desc'	: 'HAPPY ANNIVERSARY CDG!'
    }

    return render(request,'story6.html', context)

def createKegiatan(request):
    formkegiatan = KegiatanForm(request.POST)
    if request.method == "POST":
        if formkegiatan.is_valid():
            formkegiatan.save()
            return redirect ('/story6')


        return redirect('story6:index')

    context = {
         'page_title':'Story 6 Jace',
		'post_title': 'Tambahkan Kegiatan',
		'desc'	: 'HAPPY ANNIVERSARY CDG!',
        'formkegiatan' : formkegiatan,
    }

    return render(request,'create6.html', context)

def createPeserta(request, id_orang):
    formpeserta = PesertaForm(request.POST)
    if request.method == "POST":
        if formpeserta.is_valid():
            peserta = PostPeserta(ikutKegiatan = PostKegiatan.objects.get(id=id_orang),
                peserta=formpeserta.data['peserta'])
            peserta.save()    

        return redirect('story6:index')

    context = {
        'form':formpeserta
    }

    return render(request,'createOrang.html', context)

def delete(request, id_kegiatan):
    PostKegiatan.objects.filter(id=id_kegiatan).delete()
    return redirect('story6:index')


def deleteOrang(request, id_peserta):
    PostPeserta.objects.filter(id=id_peserta).delete()
    return redirect('story6:index')

story6/templates/base6.html
<!DOCTYPE html>
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style6.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/main6.css' %}">
    <title>
		{% block page_title %}

		{% endblock page_title %}
	</title>
  </head>
  <body>
    <div id="what-the-hell-is-this">
      <div class="page-title">
        <h2>{{post_title}}</h2>
        <p class="lead">
          {{desc}}</p>
      </div>
    </div>
  
	{% block contents %}

	{% endblock contents %}


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="{% static 'js/script4.js' %}"></script>
	<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

story6/templates/create6.html
{% extends "base6.html" %}
{% load static %}

{% block page_title %}
	{{page_title}}
{% endblock page_title%}

{% block contents %}
<!--===============================================================================================-->	
<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/iconic/css/material-design-iconic-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main6.css' %}">

<div class="limiter">
	<div class="container-login100" >
		<div class="wrap-login100">
			<form class="login100-form validate-form" method='post'>
			{%csrf_token%}
				<span class="login100-form-logo">
					<i class="zmdi zmdi-landscape"></i>
				</span>
				<span class="login100-form-title p-b-34 p-t-27">
					JACE
				</span>
				<div class="form-group">
				{{formkegiatan.as_table}}
				</div>
				<div class="container-login100-form-btn">
					<button type="submit" class="login100-form-btn">
						Submit
					</button>
				</div>
				</div>
			</form>
		</div>
	</div>
</div>


<div id="dropDownSelect1"></div>

<script src="{% static 'js/main4.js' %}"></script>
{% endblock contents %}

story6/templates/createOrang.html
{% extends "base6.html" %}
{% load static %}

{% block page_title %}
	{{page_title}}
{% endblock page_title%}

{% block contents %}
<!--===============================================================================================-->	
<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/iconic/css/material-design-iconic-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main6.css' %}">

<div class="limiter">
	<div class="container-login100" >
		<div class="wrap-login100">
			<form class="login100-form validate-form" method='post'>
			{%csrf_token%}
				<span class="login100-form-logo">
					<i class="zmdi zmdi-landscape"></i>
				</span>
				<span class="login100-form-title p-b-34 p-t-27">
					JACE
				</span>
				<div class="form-group">
				{{form.as_table}}
				</div>
				<div class="container-login100-form-btn">
					<button type="submit" class="login100-form-btn">
						Submit
					</button>
				</div>
				</div>
			</form>
		</div>
	</div>
</div>


<div id="dropDownSelect1"></div>

<script src="{% static 'js/main4.js' %}"></script>
{% endblock contents %}

story6/templates/story6.html
{% extends "base6.html" %}
{% load static %}
{% block page_title %}
	{{page_title}}
{% endblock page_title %}
{% block contents %}
  <!-- Font Awesome --> 
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

<!-- Google Fonts -->
<link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'><link rel="stylesheet" href="{% static 'card/style.css' %}">

<div class="container">
	<div class="row">
		{% for post in kegiatan %}	
	  <div class="col-sm-3">
		<div class="card border-dark mb-3" style="max-width: 18rem;">
		  <span class="card-header text-white bg-dark mb-3" >{{post.kegiatan}}</span>
		  
		  {% for orang in peserta %}
		  {% if orang.ikutKegiatan == post %}
		  <div class="card-content">
			<p>{{orang.peserta}},  <a href="{% url 'story6:deleteOrang' orang.id %}">Delete</a></p>
		  </div>

		  {% endif %}
		  {%endfor%}
		  <div class="card-action">
			<a href="{% url 'story6:createPeserta' post.id %}">Tambah Peserta</a>
		  </div>
		  
  
		  <div class="card-action">
			<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#delete{{post.id}}">Delete </button>
			<!-- Modal -->
				<div class="modal fade" id="delete{{post.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
					<div class="modal-dialog modal-dialog-centered" role="document">
					<div class="modal-content">
						<div class="modal-header">
						<h5 class="modal-title" id="exampleModalLongTitle">Warning</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
						</div>
						<div class="modal-body" style='color: black;'>
							Are you sure about this? This action is permanent delete this data.
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
							<form method="POST" action="{%url 'story6:delete' post.id%}"> 
							{% csrf_token %}
							<button method="POST" name="yes" class="btn btn-danger" type="submit">Delete</button>
							</form>
						</div>
					</div>
					</div>
				</div>
		  </div>
		</div>
	  </div>
	  {%endfor%}
  
	</div>
</div>


  
<a class="btn btn-primary" href="{% url 'story6:createActivity' %}"> Tambah kegiatan</a> 

  

{% endblock contents %}