story1_Jace/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story1/', include('myprofile.urls')),
    path('', include('story3ku.urls', namespace='story3')),
    path('story5/', include('story5.urls',namespace='story5')),
    path('story6/', include('story6.urls',namespace='story6')),
    path('story7/', include('story7.urls',namespace='story7')),
     path('story8/', include('story8.urls',namespace='story8')),
    path('story9/', include('story9.urls', namespace='story9')),
    path('story9/', include('django.contrib.auth.urls')),
]

story5/urls.py
from django.urls import path 
from . import views

app_name = 'story5'
urlpatterns = [
	path('delete/<str:delete_id>', views.delete, name='delete'),
	path('update/<str:update_id>', views.update, name='update'),
	path('create/', views.create, name='create'),
    path('', views.index, name='index'),

]

story5/models.py
from django.db import models

# Create your models here.
class PostMalon(models.Model):
	nama_mata_kuliah =  models.CharField(max_length = 100, )
	dosen_pengajar = models.CharField(max_length = 100, )
	jumlah_sks = models.IntegerField()
	deskripsi_mata_kuliah = models.CharField(max_length = 100,)

	LIST_TAHUN = (
		('Genap 2020/2021', 'Genap 2020/2021'),
		('Gasal 2020/2021', 'Gasal 2020/2021'),
		('Genap 2019/2020', 'Genap 2019/2020'),
		('Gasal 2019/2020', 'Gasal 2019/2020'),
	)
	semester_tahun = models.CharField (
		max_length = 100,	
		choices = LIST_TAHUN,
	)

	ruang_kelas = models.CharField(max_length = 100,)


	def __str__(self):
		return "{}.{}".format(self.id,self.nama_mata_kuliah)

story5/forms.py
from django import forms
from . models import PostMalon

# class PostForm(forms.Form):
# 	# judul = forms.CharField(max_length=100)
# 	# body = forms.CharField(widget=forms.Textarea)
# 	# category = forms.CharField(max_length=100)


class PostForm(forms.ModelForm):
	class Meta:
		model = PostMalon
		fields = [
			'nama_mata_kuliah',
			'dosen_pengajar',
			'jumlah_sks',
			'deskripsi_mata_kuliah',
			'semester_tahun',
			'ruang_kelas',
		]

story5/views.py
from django.shortcuts import render, redirect

# Create your views here.
from .forms import PostForm
from .models import PostMalon 


def update(request,update_id):
	list_update = PostMalon.objects.get(id=update_id)
	data = {
		'nama_mata_kuliah' : list_update.nama_mata_kuliah,
		'dosen_pengajar'	: list_update.dosen_pengajar,
		'jumlah_sks'		: list_update.jumlah_sks,
		'deskripsi_mata_kuliah'	: list_update.deskripsi_mata_kuliah,
		'semester_tahun'	: list_update.semester_tahun,
		'ruang_kelas'		:list_update.ruang_kelas,
}

	post_form = PostForm(request.POST or None, initial=data, instance=list_update)
	if request.method == 'POST':
		if post_form.is_valid():
			post_form.save()

			return redirect('story5:index')
			
	context = {
	'page_title': 'Story 5 Jace',
	'post_title' : 'Update Post',
	'post_form'	 : post_form,
	'desc'	: 'Untuk mengupdate mata kuliah',
	}		

	return render(request,'create.html', context)

def delete(request,delete_id):
	mendapatkan = PostMalon.objects.get(id=delete_id)
	if request.method == "POST":
		mendapatkan.delete()
		return redirect('story5:index')

def index(request):
	posts = PostMalon.objects.all()

	context = {
		'page_title':'Story 5 Jace',
		'posts': posts,
		'post_title': 'Mata Kuliahku',
		'desc'	: 'Ini adalah Mata Kuliah dari Jace!'
	}
	
	return render(request,'add.html', context)


def create(request):
	post_form = PostForm(request.POST or None)
	if request.method == 'POST':
		if post_form.is_valid():
			post_form.save()
	
		
		return redirect('story5:index')

	context = {
		'page_title': 'Story 5 Jace',
		'post_title' : 'Create Post',
		'post_form'	 : post_form,
		'desc'	: 'Untuk menambah mata kuliah'
	}
	return render(request,'create.html', context)

story5/templates/add.html
{% extends "base.html" %}
{% load static %}
{% block page_title %}
	{{page_title}}
{% endblock page_title %}
{% block contents %}
  <!-- Font Awesome --> 
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

<!-- Google Fonts -->
<link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'><link rel="stylesheet" href="{% static 'card/style.css' %}">

<div class="container">
	<div class="row">
		{% for post in posts %}	
	  <div class="col-sm-3">
		<div class="card border-dark mb-3" style="max-width: 18rem;">
		  <span class="card-header text-white bg-dark mb-3" >{{post.nama_mata_kuliah}}</span>
		  <div class="card-content">
			<p>Credits : {{post.jumlah_sks}}</p>
			<p>Lecture : {{post.dosen_pengajar}}</p>
		  </div>
		  <div class="card-action">
			<a data-toggle="modal" data-target="#exampleModalLong{{post.id}}" style="color: aqua;">Detail</a>
		  </div>
		  
		  <!-- Modal Details -->
			<div class="modal fade" id="exampleModalLong{{post.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
				<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
					<h5 class="modal-title" id="exampleModalLongTitle">Details</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					</div>
					<div class="modal-body" style="color: black;">
						<h1>{{post.nama_mata_kuliah}}</h1>
						<p>Nama Dosen : {{post.dosen_pengajar}}</p>
						<p>Credits    : {{post.jumlah_sks}}</p>
						<p>Description: {{post.deskripsi_mata_kuliah}}</p>
						<p>Period Year : {{post.semester_tahun}}</p>
						<p>Clasroom : {{post.ruang_kelas}}</p>
					</div>
					<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
					</div>
				</div>
				</div>
			</div>
  
		  <div class="card-action">
			<a class="btn btn-warning" href="{%url 'story5:update' post.id%}" >Update</a>
			<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModalCenter">Delete </button>
			<!-- Modal -->
				<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
					<div class="modal-dialog modal-dialog-centered" role="document">
					<div class="modal-content">
						<div class="modal-header">
						<h5 class="modal-title" id="exampleModalLongTitle">Warning</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
						</div>
						<div class="modal-body" style='color: black;'>
							Are you sure about this? This action is permanent delete this data.
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
							<form method="POST" action="{%url 'story5:delete' post.id%}"> 
							{% csrf_token %}
							<button method="POST" name="yes" class="btn btn-danger" type="submit">Delete</button>
							</form>
						</div>
					</div>
					</div>
				</div>
		  </div>
		</div>
	  </div>
	  {%endfor%}
  
	</div>
</div>





<!-- Dibawah pake table -->


<!-- <table class="table">
	<thead class="thead-dark">
	  <tr>
		<th scope="col">#</th>
		<th scope="col">Mata Kuliah</th>
		<th scope="col">Dosen</th>
		<th scope="col">SKS</th>
		<th scope="col">Deskripsi</th>
		<th scope="col">Semester Tahun</th>
		<th scope="col">Ruang kelas</th>
		<th scope="col">Hapus</th>
		<th scope="col">Ubah</th>
	  </tr>
	</thead>
	<tbody>
	{% for post in posts %}	
	  <tr style="color: black;">
		<th class="enjoy" scope="row">{{forloop.counter}}</th>
		<td>{{post.nama_mata_kuliah}}</td>
		<td>{{post.dosen_pengajar}}</td>
		<td>{{post.jumlah_sks}}</td>
		<td>{{post.deskripsi_mata_kuliah}}</td>
		<td>{{post.semester_tahun}}</td>
		<td>{{post.ruang_kelas}}</td>
		<td><button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModalCenter">Delete </button></td>
		   Modal -->
		<!-- <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
		<div class="modal-dialog modal-dialog-centered" role="document">
			<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLongTitle">Warning</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body" style='color: black;'>
				Are you sure about this? This action is permanent delete this data.
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				<form method="POST" action="{%url 'story5:delete' post.id%}"> 
				{% csrf_token %}
            	<button method="POST" name="yes" class="btn btn-danger" type="submit">Delete</button>
 				</form>
			</div>
			</div>
		</div>
		</div>
		<td><a class="btn btn-warning" href="{%url 'story5:update' post.id%}" >Update</a></td>
	  </tr>
	  {%endfor%}
	</tbody>
  </table>  --> 
  
<a class="btn btn-primary" href="{% url 'story5:create' %}"> Tambah </a> 
  

{% endblock contents %}

story5/templates/base.html
<!DOCTYPE html>
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style4.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/main4.css' %}">
    <title>
		{% block page_title %}

		{% endblock page_title %}
	</title>
  </head>
  <body>
  
<div class="container-fluid">
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <ul class="nav navbar-nav justify-content-center mx-auto" >
        <li><a id="len1" class="hoverable" href="{% url 'story5:index' %}">Result</a></li>
        <li><a id="len2" class="hoverable" href="{% url 'story5:create' %}">Create</a></li>
      </ul>
    </div>
  </nav>
  <div id="what-the-hell-is-this">
    <div class="page-title">
      <h2>{{post_title}}</h2>
      <p class="lead">
        {{desc}}</p>
    </div>
  </div>
</div>


	{% block contents %}

	{% endblock contents %}


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="{% static 'js/script4.js' %}"></script>
	<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

story5/templates/create.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}
	{{page_title}}
{% endblock page_title%}

{% block contents %}
<!--===============================================================================================-->	
<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/iconic/css/material-design-iconic-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main4.css' %}">

<div class="limiter">
	<div class="container-login100" style="background-image: url({% static 'images/bg-01.png' %});">
		<div class="wrap-login100">
			<form class="login100-form validate-form" method='post'>
			{%csrf_token%}
				<span class="login100-form-logo">
					<i class="zmdi zmdi-landscape"></i>
				</span>
				<span class="login100-form-title p-b-34 p-t-27">
					JACE
				</span>
				<div class="form-group">
				{{post_form.as_table}}
				</div>
				<div class="container-login100-form-btn">
					<button type="submit" class="login100-form-btn">
						Submit
					</button>
				</div>
				</div>
			</form>
		</div>
	</div>
</div>


<div id="dropDownSelect1"></div>

<script src="{% static 'js/main4.js' %}"></script>
	<!-- <form method='POST'>
		{%csrf_token%}
		<table>
			{{post_form.as_table}}
		</table>
		<button type="Submit">Kirim</button>
	</form> -->
{% endblock contents %}